# Generated by Django 5.1.4 on 2026-08-21 21:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('happened_on', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('asset_type', models.ForeignKey(blank=True, help_text='Barn, fence, generator - a catalog row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founding_costs', to='catalog.catalogitem')),
                ('branch', models.ForeignKey(blank=True, help_text='Left empty when the asset serves the whole farm.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founding_costs_of_branch', to='catalog.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('paid_by_party', models.ForeignKey(blank=True, help_text='Set when a partner or worker paid from their own pocket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founding_costs_paid', to='parties.party')),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founding_costs', to='parties.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'happened_on'], name='assets_foun_farm_id_ad7b01_idx'), models.Index(fields=['farm', 'asset_type'], name='assets_foun_farm_id_b4ea23_idx')],
            },
        ),
    ]
