# Generated by Django 5.1.5 on 2026-08-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkproduction',
            name='wasted_liters',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Litres spoiled or spilled.', max_digits=12),
        ),
    ]
