# Generated by Django 5.1.5 on 2026-08-19 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tag', models.CharField(help_text='Visible number the farm uses.', max_length=48)),
                ('name', models.CharField(blank=True, max_length=96)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=8)),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True)),
                ('acquisition', models.CharField(choices=[('born', 'Born on the farm'), ('purchased', 'Purchased'), ('gift', 'Gift'), ('opening', 'Existing at system start'), ('transfer', 'Transferred in')], default='born', max_length=16)),
                ('entered_at', models.DateField(blank=True, help_text='Date the animal joined the farm.', null=True)),
                ('exited_at', models.DateField(blank=True, help_text='Sale, death or transfer date.', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('ear_tag', models.CharField(blank=True, max_length=48)),
                ('chip_number', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=48)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('notes', models.TextField(blank=True)),
                ('is_alive', models.BooleanField(db_index=True, default=True)),
                ('is_on_farm', models.BooleanField(db_index=True, default=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals_of_type', to='catalog.catalogitem')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals_of_breed', to='catalog.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_by_father', to='animals.animal')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals_at_location', to='catalog.catalogitem')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_by_mother', to='animals.animal')),
                ('purchase_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals_with_status', to='catalog.catalogitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='AnimalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('created', 'Registered'), ('purchased', 'Purchased'), ('birth', 'Gave birth'), ('born', 'Born'), ('weight', 'Weight recorded'), ('health', 'Health event'), ('vaccine', 'Vaccination'), ('treatment', 'Treatment'), ('moved', 'Moved'), ('status', 'Status changed'), ('expense', 'Expense recorded'), ('sold', 'Sold'), ('died', 'Died'), ('note', 'Note')], db_index=True, max_length=16)),
                ('happened_on', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_events', to='ledger.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('happened_on', models.DateField(db_index=True)),
                ('total_born', models.PositiveSmallIntegerField(default=1)),
                ('born_alive', models.PositiveSmallIntegerField(default=1)),
                ('stillborn', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_births', to='animals.animal')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='births', to='animals.animal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('vaccine', 'Vaccine'), ('treatment', 'Treatment'), ('diagnosis', 'Diagnosis'), ('checkup', 'Checkup')], default='treatment', max_length=16)),
                ('happened_on', models.DateField(db_index=True)),
                ('next_due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=64)),
                ('veterinarian', models.CharField(blank=True, max_length=96)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('item', models.ForeignKey(blank=True, help_text='Vaccine or disease from the catalog.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='catalog.catalogitem')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='ledger.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on'],
            },
        ),
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_record', to='animals.animal')),
                ('birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='animals.birth')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('measured_on', models.DateField(db_index=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'animal_type', 'status'], name='animals_ani_farm_id_cb6602_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'sex', 'is_on_farm'], name='animals_ani_farm_id_c3ffe6_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('farm', 'tag'), name='uniq_animal_tag_per_farm'),
        ),
        migrations.AddIndex(
            model_name='animalevent',
            index=models.Index(fields=['animal', 'happened_on'], name='animals_ani_animal__2593fb_idx'),
        ),
        migrations.AddIndex(
            model_name='birth',
            index=models.Index(fields=['farm', 'happened_on'], name='animals_bir_farm_id_bc2578_idx'),
        ),
        migrations.AddConstraint(
            model_name='weightrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('animal', 'measured_on'), name='uniq_weight_per_day'),
        ),
    ]
