# Generated by Django 5.1.4 on 2026-08-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Breeding or fattening. Moving an animal between them is an event.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals_in_branch', to='catalog.catalogitem'),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Registered'), ('purchased', 'Purchased'), ('birth', 'Gave birth'), ('born', 'Born'), ('weight', 'Weight recorded'), ('health', 'Health event'), ('vaccine', 'Vaccination'), ('treatment', 'Treatment'), ('moved', 'Moved'), ('status', 'Status changed'), ('branch', 'Branch changed'), ('expense', 'Expense recorded'), ('sold', 'Sold'), ('died', 'Died'), ('note', 'Note')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'branch', 'is_on_farm'], name='animals_ani_farm_id_94b501_idx'),
        ),
    ]
