# Generated by Django 5.1.5 on 2026-08-19 21:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=48)),
                ('happened_on', models.DateField(db_index=True)),
                ('animals_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('transport_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('commission_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('other_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('settlement_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid in full')], default='paid', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('paid_by_party', models.ForeignKey(blank=True, help_text='Set when a worker paid from their own pocket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_paid', to='parties.party')),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_purchases', to='parties.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on'],
            },
        ),
        migrations.CreateModel(
            name='AnimalSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=48)),
                ('happened_on', models.DateField(db_index=True)),
                ('animals_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('transport_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('commission_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('received_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('settlement_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid in full')], default='paid', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_sales', to='parties.party')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('received_into_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('sale_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.catalogitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_on'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('allocated_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Unit price plus its share of transport and fees.', max_digits=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='animals.animal')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.animalpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('book_value', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Carrying cost removed from the livestock account.', max_digits=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='animals.animal')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.animalsale')),
            ],
        ),
        migrations.AddIndex(
            model_name='animalpurchase',
            index=models.Index(fields=['farm', 'happened_on'], name='operations__farm_id_201bac_idx'),
        ),
        migrations.AddIndex(
            model_name='animalsale',
            index=models.Index(fields=['farm', 'happened_on'], name='operations__farm_id_492c38_idx'),
        ),
    ]
