# Generated by Django 5.1.4 on 2026-08-22 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def grant_new_permissions(apps, schema_editor):
    """Hand the attachment and backup rights to the roles that should have them.

    Only additions: whatever else an admin has changed on a role is left alone.
    """
    from apps.accounts.models import Permission, Role
    from apps.core.models import Farm
    from apps.core.seed import DEFAULT_ROLES, seed_permissions

    seed_permissions()
    by_code = {permission.code: permission for permission in Permission.objects.all()}
    everything = list(by_code.values())

    for farm in Farm.objects.all():
        for code, _name, _name_ar, codes in DEFAULT_ROLES:
            role = Role.objects.filter(farm=farm, code=code).first()
            if role is None:
                continue
            wanted = everything if codes == "*" else [
                by_code[permission] for permission in codes if permission in by_code
            ]
            role.permissions.add(*wanted)


def noop(apps, schema_editor):
    """Nothing to undo: the rows added here are safe to keep."""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_finance_delete_permission"),
        ('core', '0002_branches_stores_and_milk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(grant_new_permissions, noop),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_type', models.CharField(db_index=True, max_length=32)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('document', 'Document')], default='document', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='Decoded size in bytes.')),
                ('data', models.TextField(help_text='The file itself, inlined as a data URI.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'subject_type', 'subject_id'], name='core_attach_farm_id_1b96af_idx'), models.Index(fields=['farm', 'kind'], name='core_attach_farm_id_ea2393_idx')],
            },
        ),
    ]
