# Generated by Django 5.1.5 on 2026-08-19 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('name_ar', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=16)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='catalog.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('opening', 'Opening balance'), ('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer between accounts'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('capital', 'Capital contribution'), ('withdrawal', 'Withdrawal'), ('loan', 'Loan'), ('settlement', 'Settlement'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=16)),
                ('min_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Entries at or above this amount require approval.', max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.BigIntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('opening', 'Opening balance'), ('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer between accounts'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('capital', 'Capital contribution'), ('withdrawal', 'Withdrawal'), ('loan', 'Loan'), ('settlement', 'Settlement'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('void', 'Void')], db_index=True, default='posted', max_length=16)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total debits of the entry, for listing and filtering.', max_digits=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('subject_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.currency')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('subject_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['entry', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedCommand',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=64)),
                ('result_type', models.CharField(blank=True, max_length=64)),
                ('result_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_commands', to='core.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['farm', 'type', 'is_active'], name='ledger_acco_farm_id_d26d1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('farm', 'code'), name='uniq_account_code_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('farm', 'kind', 'currency'), name='uniq_approval_rule'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['farm', 'kind', 'date'], name='ledger_jour_farm_id_e03670_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['subject_type', 'subject_id'], name='ledger_jour_subject_af257a_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('farm', 'number'), name='uniq_entry_number_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('farm', 'idempotency_key'), name='uniq_entry_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['account'], name='ledger_ledg_account_da3772_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['subject_type', 'subject_id'], name='ledger_ledg_subject_d5da72_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_line_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='ledger_line_single_side'),
        ),
    ]
