# Generated by Django 5.1.4 on 2026-08-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerline',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='catalog.catalogitem'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['branch'], name='ledger_ledg_branch__414367_idx'),
        ),
    ]
