# Generated by Django 5.1.5 on 2026-08-19 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('brand_name', models.CharField(blank=True, max_length=96)),
                ('brand_tagline', models.CharField(blank=True, max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('font_family', models.CharField(default='Cairo', max_length=64)),
                ('font_scale', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('corner_radius', models.PositiveSmallIntegerField(default=12, help_text='0 = sharp corners.')),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('sidebar', models.JSONField(blank=True, default=list)),
                ('dashboard_widgets', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('farm', 'status'), name='uniq_theme_per_status')],
            },
        ),
    ]
