# Generated by Django 5.1.5 on 2026-08-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
