# Generated by Django 5.1.5 on 2026-08-19 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entity', models.CharField(choices=[('animal', 'Animal'), ('expense', 'Expense'), ('income', 'Income'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('party', 'Supplier / customer'), ('asset', 'Asset'), ('inventory_item', 'Inventory item'), ('partner', 'Partner')], db_index=True, max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('label_ar', models.CharField(blank=True, max_length=128)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('number', 'Number'), ('decimal', 'Decimal'), ('currency', 'Currency'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Yes / No'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi select'), ('radio', 'Radio'), ('file', 'File'), ('image', 'Image'), ('relation', 'Relation'), ('percentage', 'Percentage')], default='text', max_length=24)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_list', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entity', models.CharField(choices=[('animal', 'Animal'), ('expense', 'Expense'), ('income', 'Income'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('party', 'Supplier / customer'), ('asset', 'Asset'), ('inventory_item', 'Inventory item'), ('partner', 'Partner')], db_index=True, max_length=32)),
                ('object_id', models.UUIDField(db_index=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customfields.fielddefinition')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['farm', 'entity', 'is_active'], name='customfield_farm_id_c1182e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('farm', 'entity', 'key'), name='uniq_field_key_per_entity'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['entity', 'object_id'], name='customfield_entity_6ba0af_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('definition', 'object_id'), name='uniq_value_per_object'),
        ),
    ]
